<?php

namespace BieliNet\Bundle\MicroCrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGroupRepository extends EntityRepository
{
}
