acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

bieli_net_micro_crm:
    resource: "@BieliNetMicroCrmBundle/Controller/"
    type:     annotation
    prefix:   /micro-crm

MopaBootstrapSandbox:
    resource: "@MopaBootstrapSandboxBundle/Resources/config/routing.yml"

#liip_theme:
#    resource: "@LiipThemeBundle/Resources/config/routing.xml"
#    prefix: /theme

